### ISSUE TITLE
Libzim for Termux app in android

### ISSUE THREAD

**Issue by sobaee** [openzim/libzim#391]
I can't install libzim in Termux app (aarch64)
I already installed app prerequisites and dependencies.
You may tell me whats the required versions of the dependecies, or how to install it manually from the source.

 
Please help!

**Comment by kelson42** [comment]
@sobaee Can you please put here the whole commands an log you are running please?

**Comment by sobaee** [comment]
$ pip install libzim
Collecting libzim
  Using cached libzim-0.0.3.post0.tar.gz (103 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-cdake3g2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 35.0.2' 'wheel >= 0.29.0' twine 'cython == 0.29.6'
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/data/data/com.termux/files/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 22, in <module>
      from pip._internal.req.constructors import (
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 10, in <module>
      from .req_install import InstallRequirement
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 10, in <module>
      import uuid
    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uuid.py", line 138
      if not 0 <= time_low < 1<<32L:
                                  ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-cdake3g2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 35.0.2' 'wheel >= 0.29.0' twine 'cython == 0.29.6' Check the logs for full command output.
$

**Comment by kelson42** [comment]
@sobaee I'm moving the ticket to the python binding which is the right place.
