### ISSUE TITLE
Deb packaging CI is failing.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#615]
See https://github.com/openzim/libzim/runs/3398272391?check_suite_focus=true

```
 /usr/bin/docker run --name c9e0367bdaeba10cf84c6faee992b51d4cbfb5_a60a88 --label c9e036 --workdir /github/workspace --rm -e INPUT_FULLNAME -e INPUT_EMAIL -e INPUT_DISTRO -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/libzim/libzim":"/github/workspace" c9e036:7bdaeba10cf84c6faee992b51d4cbfb5  "Kiwix builder" "release+launchpad@kiwix.org" "debian-unstable"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@6fe45d741597.(none)')
Traceback (most recent call last):
New version: 7.0.0+git202108230833.fcd5025~unstable
  File "/auto_dch.py", line 101, in <module>
    main()
  File "/auto_dch.py", line 97, in main
    subprocess.check_call(['git', 'commit', '-a', '-m', 'New automated build'])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'commit', '-a', '-m', 'New automated build']' returned non-zero exit status 128.
```

**Comment by legoktm** [comment]
It'll take about ~25 minutes for the new images to be pushed to Docker Hub, I'll retry the builds once that happens.

**Comment by legoktm** [comment]
https://github.com/openzim/libzim/runs/3402012459 looks good now. Sorry about that!
